In [3]:
import numpy as np

## numpy is used to convert all data in matrixes, data manipulations..


In [19]:
l = [1,2,3,4,4]
type(l)

list

In [20]:
arr = np.array(l) ## list is converted in to array

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]]) #### 2d array -> x and y axies values presented in array format...

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
### symentry dimension data should be there in list.......

arr2 = np.array([[[1., 2., 3.],[4., 0.5, 6. ]]]) ### 3d array - x y and z(depth of 3d object) axis presentrd in array format

NameError: name 'np' is not defined

In [12]:
arr.ndim

1

In [13]:
arr1.ndim

2

In [14]:
arr2.ndim

3

In [4]:
arr2 = np.array([[[1., 2., 3.],[4., 0.5, 6. ]],[[1., 2., 3.],[4., 0.5, 6. ]],[[1., 2., 3.],[4., 0.5, 6. ]] ])

In [5]:
arr2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [6]:
## 3 d array is combination of 2d on different axies as 2d records are presented on pages of book(3d example..)
arr2.ndim

3

In [7]:
l =[1,2,3,4,5]
np.asarray(l) # convert list as array in 1-d

array([1, 2, 3, 4, 5])

In [15]:
m = np.matrix(l) ## matrix will create as 2d array.. u see [[ ]]
m

matrix([[1, 2, 3, 4, 5]])

In [14]:
np.asanyarray(m)

matrix([[1, 2, 3, 4, 5]])

In [17]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [21]:
arr = np.array(l) ## list is converted in to array

In [22]:
a1=arr ## this is called shawllo copy. mutable refelection of changes will be in both cariable.. stored in same memory..

In [23]:
a1

array([1, 2, 3, 4, 4])

In [24]:
arr[0]

1

In [25]:
arr[0]=10 
a1

array([10,  2,  3,  4,  4])

In [26]:
a1[3] = 50
arr

array([10,  2,  3, 50,  4])

In [29]:
## arrays are non mutable....... -- this is example of deep copy
a2 = np.copy(a1)
a2

array([10,  2,  3, 50,  4])

In [30]:
a2[2] = 30
a2

array([10,  2, 30, 50,  4])

In [31]:
a1

array([10,  2,  3, 50,  4])

In [33]:
## used to generate data .... 3 rows and 4 column rander data based on equations
np.fromfunction(lambda i,j : i==j,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [34]:
np.random.rand(2,3) ### 2 rows and 3 column to generate random data

array([[0.94663374, 0.08867626, 0.00606067],
       [0.37865261, 0.10650569, 0.19727374]])

In [36]:
np.random.rand(5,3,2) #### 3x2 2d array in 5 rows i.e 3d array

array([[[0.04006579, 0.13166196],
        [0.59806629, 0.18648748],
        [0.42994352, 0.72238688]],

       [[0.06231749, 0.98341291],
        [0.5512784 , 0.41640972],
        [0.65770488, 0.13207297]],

       [[0.85712704, 0.04199653],
        [0.47773902, 0.92669384],
        [0.8328611 , 0.06914654]],

       [[0.47082871, 0.8429277 ],
        [0.21853278, 0.40636608],
        [0.23383148, 0.56154364]],

       [[0.67916408, 0.44265032],
        [0.0682316 , 0.73043815],
        [0.45688673, 0.18770142]]])

In [37]:
np.random.rand(2,4,4) 

array([[[0.88145752, 0.2251765 , 0.75360285, 0.79773817],
        [0.09888093, 0.06765381, 0.31756555, 0.55683746],
        [0.59075156, 0.81103325, 0.66832464, 0.85367701],
        [0.83654396, 0.21898188, 0.85543677, 0.74199074]],

       [[0.08856335, 0.79019698, 0.35449036, 0.68464373],
        [0.34499046, 0.23674604, 0.38737713, 0.86197522],
        [0.90376767, 0.9334759 , 0.84073292, 0.08886323],
        [0.50269512, 0.69124877, 0.93490947, 0.8815965 ]]])

In [38]:
np.random.rand(3,4,4) 

array([[[0.75757103, 0.376302  , 0.881944  , 0.56956974],
        [0.25675924, 0.52318544, 0.62912022, 0.60640077],
        [0.77892154, 0.19363649, 0.41650712, 0.63184631],
        [0.88507426, 0.93213078, 0.15312322, 0.620817  ]],

       [[0.32538543, 0.1143745 , 0.65005579, 0.14611653],
        [0.20005129, 0.73606424, 0.53889992, 0.34908699],
        [0.54158568, 0.52490419, 0.75241956, 0.07996313],
        [0.50124774, 0.93804707, 0.50444925, 0.39265417]],

       [[0.69567424, 0.95287663, 0.41580443, 0.78741449],
        [0.0340637 , 0.51070943, 0.56943421, 0.23950408],
        [0.3840125 , 0.67633871, 0.65721522, 0.97029225],
        [0.7526173 , 0.05216415, 0.85275997, 0.32416423]]])

In [39]:
np.random.rand(3,4,4,2) # 4d array 

array([[[[0.79798848, 0.83716807],
         [0.77007208, 0.11808569],
         [0.00921259, 0.95210835],
         [0.81350403, 0.20824261]],

        [[0.47794584, 0.36731141],
         [0.42032463, 0.58697865],
         [0.97243387, 0.39256107],
         [0.71231467, 0.16048661]],

        [[0.21373695, 0.05138559],
         [0.7467637 , 0.54695999],
         [0.58038579, 0.01428268],
         [0.06970264, 0.26502018]],

        [[0.68975584, 0.7319749 ],
         [0.60354462, 0.35827355],
         [0.52334465, 0.15880955],
         [0.5501996 , 0.0450923 ]]],


       [[[0.98657757, 0.04015232],
         [0.91309222, 0.57641359],
         [0.36747816, 0.1781216 ],
         [0.14647214, 0.15304569]],

        [[0.65661858, 0.92622407],
         [0.29880668, 0.56891131],
         [0.70236423, 0.33394687],
         [0.26604501, 0.29638716]],

        [[0.0812027 , 0.26283826],
         [0.35493587, 0.66551288],
         [0.42827534, 0.08724528],
         [0.73540245, 0.63862887]],

    

In [40]:
np.random.randn(3,4,4) # generate data based on standard normal distribution that it mean 0 to std 1 

array([[[ 0.83172454,  0.57485722, -1.3801431 , -0.03920608],
        [-0.2767303 ,  0.05314848,  0.35400877,  1.38805814],
        [ 0.07657031, -0.2020136 ,  1.20343667, -0.34481343],
        [ 0.94205912,  0.62285217,  0.79431428, -0.15785916]],

       [[-2.70552668, -0.01994142,  1.35935439,  0.28706192],
        [ 1.67962479,  1.13031758,  1.78869802,  1.14331535],
        [-0.27712631,  0.56312557,  1.76664613, -0.92206703],
        [ 1.37157167, -1.42166372,  0.18461354,  0.75130137]],

       [[ 0.59201646,  0.44239507, -0.95576674, -1.30185861],
        [ 0.24176194, -0.77741045, -0.40923246, -0.12510785],
        [-0.11040359, -0.0402393 , -0.75507652,  0.15806395],
        [-2.42535478, -0.46475718,  0.18762589, -0.38311205]]])

In [42]:
np.random.randint(0,10,(4,4)) ## (min, max,  2d array size) generate data as int... 

array([[7, 7, 9, 6],
       [1, 4, 0, 2],
       [9, 5, 4, 6],
       [2, 2, 9, 6]])

In [43]:
np.random.randint(0,10,(4,4,2)) ### 3d array

array([[[8, 9],
        [3, 2],
        [1, 1],
        [0, 9]],

       [[8, 7],
        [1, 4],
        [2, 1],
        [0, 1]],

       [[3, 7],
        [9, 3],
        [9, 2],
        [7, 6]],

       [[5, 3],
        [1, 9],
        [1, 0],
        [1, 4]]])

In [44]:
d = np.random.randn(3,4)

In [45]:
import pandas as pd

In [46]:
pd.DataFrame(d) # 2d in dataframe bcas it in 2d

0         1         2         3
0 -0.465764  0.453772 -0.187656 -1.099683
1 -1.206286 -1.193232  1.576218 -0.657408
2  1.388199  0.475381 -0.110092 -1.036634

In [47]:
d = np.random.randn(3,4,2)

In [48]:
d

array([[[ 0.52690988,  0.41059595],
        [-0.30106866,  1.11671369],
        [-0.0917721 , -2.05022557],
        [ 0.07693024,  1.25382783]],

       [[ 0.19008869, -2.06297689],
        [-0.97101273, -0.62041389],
        [ 2.02520751,  0.44987289],
        [ 1.3290434 , -0.93932275]],

       [[-0.02877119, -0.45358995],
        [-0.56254019, -0.24865143],
        [-0.12082115, -0.30481282],
        [-0.66848451, -0.77962636]]])

In [49]:
pd.DataFrame(d) ### 2d cant be converted into dataframe which is 2d

ValueError: Must pass 2-d input. shape=(3, 4, 2)

In [50]:
# so 3d need to convert in 2d so reshape function can be used..
d.reshape(12,2) ### bcas d has 24 elements in d so multiply of 24 can be used as a reshape...

array([[ 0.52690988,  0.41059595],
       [-0.30106866,  1.11671369],
       [-0.0917721 , -2.05022557],
       [ 0.07693024,  1.25382783],
       [ 0.19008869, -2.06297689],
       [-0.97101273, -0.62041389],
       [ 2.02520751,  0.44987289],
       [ 1.3290434 , -0.93932275],
       [-0.02877119, -0.45358995],
       [-0.56254019, -0.24865143],
       [-0.12082115, -0.30481282],
       [-0.66848451, -0.77962636]])

In [51]:
d.reshape(8,-1) ### convert into internally possible dimension...

array([[ 0.52690988,  0.41059595, -0.30106866],
       [ 1.11671369, -0.0917721 , -2.05022557],
       [ 0.07693024,  1.25382783,  0.19008869],
       [-2.06297689, -0.97101273, -0.62041389],
       [ 2.02520751,  0.44987289,  1.3290434 ],
       [-0.93932275, -0.02877119, -0.45358995],
       [-0.56254019, -0.24865143, -0.12082115],
       [-0.30481282, -0.66848451, -0.77962636]])